### ISSUE TITLE
Timezone crash

### ISSUE THREAD

**Issue by sdefauw** [sdefauw/BridgeOrigin#14]
On some platform the time zone crash the execution. Changes made in ece00e8 break the packet processing.

**Comment by sdefauw** [comment]
Stack trace of the issue
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/brorig/webserver.py", line 378, in run
    self.packet_trigger()
  File "/brorig/webserver.py", line 338, in packet_trigger
    set=self.__gen_packet_list(self.ws.client.network.nodes)
  File "/brorig/webserver.py", line 313, in __gen_packet_list
    } for (item, p) in p_list_to_transfer]
  File "/brorig/webserver.py", line 295, in time_format
    return calendar.timegm(UTC.localize(t).timetuple()) * 1e3 + t.microsecond / 1e3 if t else None
  File "/usr/local/lib/python2.7/dist-packages/pytz/__init__.py", line 227, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)
```

**Comment by sdefauw** [comment]
Indeed in the case the time zone is set and python don't want to change this value.
